language: cpp
complier: g++
sudo: required
before-install:
    - chmod +x .build.sh
    - chmod +x .protobuf_dl.sh
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9
            - libboost-dev
            - libboost-system-dev
            - git
            - autoconf
            - automake
            - libtool
            - curl
            - cmake
            - make
            - unzip
install:
    - CC=gcc-4.9 CXX=g++-4.9
script: travis_wait ./.build.sh

#what?
