language: cpp
complier: g++
sudo: required
before-install:
    - chmod +x .build.sh
    - chmod +x .protobuf_dl.sh
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5
            - libboost-dev
            - libboost-system-dev
            - git
            - autoconf
            - automake
            - libtool
            - curl
            - cmake
            - make
            - unzip
install:
    - CC=gcc-5 CXX=g++-5
script: travis_wait 30 ./.build.sh

#what?
